/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CarModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4654904471000690868L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CarModel\",\"namespace\":\"kafka.avro\",\"fields\":[{\"name\":\"make\",\"type\":\"string\"},{\"name\":\"model\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CarModel> ENCODER =
      new BinaryMessageEncoder<CarModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CarModel> DECODER =
      new BinaryMessageDecoder<CarModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CarModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CarModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CarModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CarModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CarModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CarModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CarModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CarModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence make;
   private java.lang.CharSequence model;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CarModel() {}

  /**
   * All-args constructor.
   * @param make The new value for make
   * @param model The new value for model
   */
  public CarModel(java.lang.CharSequence make, java.lang.CharSequence model) {
    this.make = make;
    this.model = model;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return make;
    case 1: return model;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: make = (java.lang.CharSequence)value$; break;
    case 1: model = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'make' field.
   * @return The value of the 'make' field.
   */
  public java.lang.CharSequence getMake() {
    return make;
  }


  /**
   * Sets the value of the 'make' field.
   * @param value the value to set.
   */
  public void setMake(java.lang.CharSequence value) {
    this.make = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Creates a new CarModel RecordBuilder.
   * @return A new CarModel RecordBuilder
   */
  public static kafka.avro.CarModel.Builder newBuilder() {
    return new kafka.avro.CarModel.Builder();
  }

  /**
   * Creates a new CarModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CarModel RecordBuilder
   */
  public static kafka.avro.CarModel.Builder newBuilder(kafka.avro.CarModel.Builder other) {
    if (other == null) {
      return new kafka.avro.CarModel.Builder();
    } else {
      return new kafka.avro.CarModel.Builder(other);
    }
  }

  /**
   * Creates a new CarModel RecordBuilder by copying an existing CarModel instance.
   * @param other The existing instance to copy.
   * @return A new CarModel RecordBuilder
   */
  public static kafka.avro.CarModel.Builder newBuilder(kafka.avro.CarModel other) {
    if (other == null) {
      return new kafka.avro.CarModel.Builder();
    } else {
      return new kafka.avro.CarModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CarModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CarModel>
    implements org.apache.avro.data.RecordBuilder<CarModel> {

    private java.lang.CharSequence make;
    private java.lang.CharSequence model;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(kafka.avro.CarModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.make)) {
        this.make = data().deepCopy(fields()[0].schema(), other.make);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.model)) {
        this.model = data().deepCopy(fields()[1].schema(), other.model);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CarModel instance
     * @param other The existing instance to copy.
     */
    private Builder(kafka.avro.CarModel other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.make)) {
        this.make = data().deepCopy(fields()[0].schema(), other.make);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.model)) {
        this.model = data().deepCopy(fields()[1].schema(), other.model);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'make' field.
      * @return The value.
      */
    public java.lang.CharSequence getMake() {
      return make;
    }


    /**
      * Sets the value of the 'make' field.
      * @param value The value of 'make'.
      * @return This builder.
      */
    public kafka.avro.CarModel.Builder setMake(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.make = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'make' field has been set.
      * @return True if the 'make' field has been set, false otherwise.
      */
    public boolean hasMake() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'make' field.
      * @return This builder.
      */
    public kafka.avro.CarModel.Builder clearMake() {
      make = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public kafka.avro.CarModel.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.model = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public kafka.avro.CarModel.Builder clearModel() {
      model = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CarModel build() {
      try {
        CarModel record = new CarModel();
        record.make = fieldSetFlags()[0] ? this.make : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.model = fieldSetFlags()[1] ? this.model : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CarModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CarModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CarModel>
    READER$ = (org.apache.avro.io.DatumReader<CarModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.make);

    out.writeString(this.model);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.make = in.readString(this.make instanceof Utf8 ? (Utf8)this.make : null);

      this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.make = in.readString(this.make instanceof Utf8 ? (Utf8)this.make : null);
          break;

        case 1:
          this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










