version: '3.7'

services:
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - ${GLOBAL_NETWORK:-minio}
    command: server /data --console-address ":9001"

networks:
  application:
    driver: bridge